CREATE FUNCTION [dbo].[FN_SEGUNDOS_EM_HORAS] 
(
	@ORIGVALUE INT
)

RETURNS VARCHAR(MAX)

AS
BEGIN

/*Objetivo: Obter um valor inteiro representando segundos, e converter para horas  no formato hh:mm:ss*/

	DECLARE @CONVERTIDO VARCHAR(MAX)
	DECLARE @FORMATADO VARCHAR(MAX)
	
	--SET @ORIGVALUE = 86400; -- 24 HORAS
	--SET @ORIGVALUE = 360000; -- 100 HORAS
	
	SELECT @CONVERTIDO = REPLACE(STR(@ORIGVALUE/3600,LEN(LTRIM(@ORIGVALUE/3600))+ABS(SIGN(@ORIGVALUE/359999)-1)) + ':' + STR((@ORIGVALUE/60)%60,2) + ':' + STR(@ORIGVALUE%60,2),' ','0')
	
	
	
	IF LEN(@CONVERTIDO) <= 8 OR (LEN(@CONVERTIDO) > 8 AND LEFT(@CONVERTIDO,1) <> '0')
	
		SET @FORMATADO = @CONVERTIDO
	
	ELSE
	
		SET @FORMATADO = RIGHT(@CONVERTIDO, 8)
	
	RETURN @FORMATADO


END


