
CREATE PROCEDURE [dbo].[SP_ALTERA_CHAMADO]
(
	@CD_CHAMADO INT = NULL,
	@CD_STATUS_CHAMADO INT = NULL,
	@CD_ORIGEM_CHAMADO INT = NULL,
	@CD_SISTEMA INT = NULL,
	@CD_MODULO INT = NULL,
	@DATA_HORA_ABERTURA DATETIME = NULL,
	@CD_USUARIO INT = NULL,
	@DESCRICAO VARCHAR(MAX) = NULL,
	@CD_SOLICITACAO INT = NULL,
	@CD_MOTIVO_CANCELAMENTO INT = NULL,
	@BL_TRANSFORMAR_OS INT = NULL,
	@DH_FIM_ATENDIMENTO DATETIME = NULL,
	@OBS_MOTIVO_CANCELAMENTO VARCHAR(MAX) = NULL,
	@DH_ALTERACAO DATETIME = NULL,
	@CD_EMPRESA INT = NULL,
	@CD_APROVACAO INT = NULL,
	@MOTIVO_REPROVACAO VARCHAR(500) = NULL,
	@MOTIVO VARCHAR(500) = NULL,
	@RESPONSAVEL_REPROVACAO INT = NULL,
	@CD_USUARIO_ABERTURA INT = NULL,
	@MOTIVO_APROVACAO VARCHAR(MAX) = NULL, 
	@RESPONSAVEL_APROVACAO INT = NULL,
	@MOTIVO_CONCLUSAO VARCHAR(MAX) = NULL, 
	@RESPONSAVEL_CONCLUSAO INT = NULL,
	@MOTIVO_REABERTURA VARCHAR(MAX) = NULL, 
	@RESPONSAVEL_REABERTURA INT = NULL,
	@CD_PRIORIDADE INT = NULL,
	@CD_FILA INT = NULL,
	@CD_RESPONSAVEL INT = NULL
)


/* Objetivo: Procedure dedicada a edição dos chamados da tabela de chamados */
AS
BEGIN

		SET TRAN ISOLATION LEVEL READ UNCOMMITTED
        
	
		UPDATE 
			CHAMADO

		SET

			CD_STATUS_CHAMADO       = CASE WHEN @CD_FILA IS NOT NULL AND @CD_RESPONSAVEL IS NULL AND @CD_STATUS_CHAMADO IS NULL THEN 1
									       ELSE ISNULL(@CD_STATUS_CHAMADO,CD_STATUS_CHAMADO) END,

			CD_SISTEMA              = ISNULL (@CD_SISTEMA, CD_SISTEMA),
			CD_MODULO               = ISNULL (@CD_MODULO, CD_MODULO),
			DH_INICIO_ATENDIMENTO   = ISNULL(DH_INICIO_ATENDIMENTO,GETDATE()),
			
			DH_ALTERACAO            =  CASE WHEN @CD_FILA IS NULL THEN DATA_HORA_ABERTURA
										    WHEN @CD_FILA IS NOT NULL AND @CD_STATUS_CHAMADO IN(1,2,7,9) THEN GETDATE() 
										    WHEN @CD_STATUS_CHAMADO NOT IN (2,7) THEN NULL
										
										END,

			DESCRICAO               = ISNULL (@DESCRICAO, DESCRICAO),
			CD_SOLICITACAO          = ISNULL (@CD_SOLICITACAO, CD_SOLICITACAO),
			CD_MOTIVO_CANCELAMENTO  = ISNULL (@CD_MOTIVO_CANCELAMENTO, CD_MOTIVO_CANCELAMENTO),
			CD_USUARIO_ABERTURA     = ISNULL(@CD_USUARIO_ABERTURA, CD_USUARIO_ABERTURA),
			DH_FIM_ATENDIMENTO      = CASE WHEN @CD_STATUS_CHAMADO IN (5,8) THEN GETDATE()
									       WHEN @CD_STATUS_CHAMADO IS NULL THEN DH_FIM_ATENDIMENTO
									       ELSE NULL
								        END,
			
            OBS_MOTIVO_CANCELAMENTO = ISNULL (@OBS_MOTIVO_CANCELAMENTO,OBS_MOTIVO_CANCELAMENTO),
			CD_RESPONSAVEL          = CASE WHEN @CD_RESPONSAVEL    = 0 THEN NULL ELSE ISNULL(@CD_RESPONSAVEL,CD_RESPONSAVEL) END,
			CD_USUARIO_FINALIZADO   = CASE WHEN @CD_STATUS_CHAMADO = 4 THEN @CD_USUARIO ELSE CD_USUARIO_FINALIZADO END,
			CD_USUARIO_CANCELADO    = CASE WHEN @CD_STATUS_CHAMADO = 5 THEN @CD_USUARIO ELSE CD_USUARIO_CANCELADO END,
			CD_USUARIO_ARQUIVADO    = CASE WHEN @CD_STATUS_CHAMADO = 6 THEN @CD_USUARIO ELSE CD_USUARIO_ARQUIVADO END,
			CD_EMPRESA              = ISNULL(@CD_EMPRESA,CD_EMPRESA),
			CD_APROVACAO            = ISNULL(@CD_APROVACAO,CD_APROVACAO),
			MOTIVO_REPROVACAO       = ISNULL(@MOTIVO_REPROVACAO,MOTIVO_REPROVACAO),
			MOTIVO                  = ISNULL(@MOTIVO, MOTIVO),
			RESPONSAVEL_REPROVACAO  = CASE WHEN @CD_APROVACAO = 0 AND @MOTIVO_REPROVACAO IS NOT NULL THEN @CD_USUARIO ELSE RESPONSAVEL_REPROVACAO END,
			MOTIVO_APROVACAO        = ISNULL(@MOTIVO_APROVACAO,MOTIVO_APROVACAO), 
			RESPONSAVEL_APROVACAO   = CASE WHEN @CD_APROVACAO = 1 AND @MOTIVO_CONCLUSAO IS NULL THEN @CD_USUARIO ELSE RESPONSAVEL_APROVACAO END, 
			MOTIVO_CONCLUSAO        = ISNULL(@MOTIVO_CONCLUSAO,MOTIVO_CONCLUSAO),
			RESPONSAVEL_CONCLUSAO   = CASE WHEN @MOTIVO_CONCLUSAO IS NOT NULL THEN @CD_USUARIO ELSE RESPONSAVEL_CONCLUSAO END,
			MOTIVO_REABERTURA       = ISNULL(@MOTIVO_REABERTURA,MOTIVO_REABERTURA),
			RESPONSAVEL_REABERTURA  = CASE WHEN @MOTIVO_REABERTURA IS NOT NULL THEN @CD_USUARIO ELSE RESPONSAVEL_REABERTURA END,
			CD_PRIORIDADE           = ISNULL(@CD_PRIORIDADE,CD_PRIORIDADE),
			CD_FILA                 = CASE WHEN @CD_FILA = 0 THEN NULL ELSE ISNULL(@CD_FILA,CD_FILA) END

		WHERE
			CD_CHAMADO = @CD_CHAMADO

		--SELECT @CD_CHAMADO AS CD
        
        SELECT * FROM CHAMADO WHERE CD_CHAMADO = @CD_CHAMADO
    
    -------------------------------------------
	-- INSERE CHAMADO NA TABELA DE HISTORICO --
    -------------------------------------------

	INSERT INTO CHAMADO_HISTORICO 
	(
		 CD_CHAMADO
		,CD_STATUS_CHAMADO
		,CD_SISTEMA
		,CD_MODULO
		,CD_SOLICITACAO
		,CD_MOTIVO_CANCELAMENTO
		,OBS_MOTIVO_CANCELAMENTO
		,DATA_HORA_ABERTURA
		,CD_USUARIO_ABERTURA
		,DESCRICAO
		,DH_INICIO_ATENDIMENTO
		,DH_FIM_ATENDIMENTO
		,DH_ALTERACAO
		,CD_USUARIO_FINALIZADO
		,CD_USUARIO_CANCELADO
		,CD_RESPONSAVEL
		,CD_EMPRESA
		,MOTIVO
		,CD_APROVACAO
		,MOTIVO_REPROVACAO
		,MOTIVO_CONCLUSAO
		,RESPONSAVEL_REPROVACAO
		,RESPONSAVEL_CONCLUSAO
		,MOTIVO_APROVACAO
		,RESPONSAVEL_APROVACAO
		,MOTIVO_REABERTURA
		,RESPONSAVEL_REABERTURA
		,CD_PRIORIDADE
		,CD_FILA
		,CD_USUARIO_ALTERACAO
		,CD_GRUPO_EMPRESA
	)
	
	
	SELECT   
		 CD_CHAMADO
		,CD_STATUS_CHAMADO
		,CD_SISTEMA
		,CD_MODULO
		,CD_SOLICITACAO
		,CD_MOTIVO_CANCELAMENTO
		,OBS_MOTIVO_CANCELAMENTO
		,DATA_HORA_ABERTURA
		,CD_USUARIO_ABERTURA
		,DESCRICAO
		,DH_INICIO_ATENDIMENTO
		,DH_FIM_ATENDIMENTO
		,DH_ALTERACAO
		,CD_USUARIO_FINALIZADO
		,CD_USUARIO_CANCELADO
		,CD_RESPONSAVEL
		,CD_EMPRESA
		,MOTIVO
		,CD_APROVACAO
		,MOTIVO_REPROVACAO
		,MOTIVO_CONCLUSAO
		,RESPONSAVEL_REPROVACAO
		,RESPONSAVEL_CONCLUSAO
		,MOTIVO_APROVACAO
		,RESPONSAVEL_APROVACAO
		,MOTIVO_REABERTURA
		,RESPONSAVEL_REABERTURA
		,CD_PRIORIDADE
		,CD_FILA
		,@CD_USUARIO
		,CD_GRUPO_EMPRESA
	
	FROM 
		CHAMADO 
	
	WHERE 
		CD_CHAMADO = @CD_CHAMADO
END
