

CREATE VIEW VW_CLASSIFICACAO_CAMPEONATO AS 

SELECT 
	CLASSIFICACAO,
	EQUIPE,
	CAST([1] AS INT) AS PONTOS,
	CAST([2] AS INT) AS JOGOS,
	CAST([3] AS INT) AS VITORIAS,
	CAST([4] AS INT) AS EMPATES,
	CAST([5] AS INT) AS DERROTAS,
	CAST([6] AS INT) AS GOLS_FEITOS,
	CAST([7] AS INT) AS GOLS_SOFRIDOS,
	CAST([8] AS INT) AS SALDO_GOLS,
	CAST([9] AS INT) AS APROVEITAMENTO,
	CAST (DT_ATUALIZACAO AS DATE) AS DT_ATUALIZACAO,
	NUM_RODADA
	
	

FROM (
    SELECT
        CLASSIFICACAO,
        EQUIPE,
        VALUE AS VALOR,
        ROW_NUMBER() OVER (PARTITION BY CLASSIFICACAO ORDER BY CLASSIFICACAO ) AS ID,
		DT_ATUALIZACAO,
		NUM_RODADA
    FROM
        TB_CLASSIFICACAO
    CROSS APPLY STRING_SPLIT(VALORES, ',')
) AS T
PIVOT 
(
    MAX(VALOR)
    FOR ID IN ([1], [2], [3], [4], [5], [6], [7], [8], [9])
) AS PIVOTABLE





